site:
  title: 'GraphRAG Workshop: Neo4j & AWS Bedrock'
  url: https://neo4j-partners.github.io/neo4j-sec-filings-graphrag-workshop/workshop
  start_page: neo4j-sec-filings-graphrag-workshop::index.adoc

content:
  sources:
  - url: ..
    branches: HEAD
    start_path: site

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    source-highlighter: highlight.js

output:
  dir: ./build/site
  clean: true
